### ISSUE TITLE
ImportError: cannot import name 'NoopSelectQuery'

### ISSUE THREAD

**Issue by kobelover** [kszucs/aiopeewee#12]
hi, when i run [sanic aiopeewee example](https://github.com/channelcat/sanic/wiki/Examples#aiopeewee), I get 
```
Traceback (most recent call last):
  File "/Users/name/PycharmProjects/sanic-demo/sanic_aiopeewee.py", line 4, in <module>
    from aiopeewee import AioModel, AioMySQLDatabase, model_to_dict
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiopeewee/__init__.py", line 1, in <module>
    from .model import AioModel
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiopeewee/model.py", line 3, in <module>
    from .query import (AioSelectQuery, AioUpdateQuery, AioInsertQuery,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiopeewee/query.py", line 2, in <module>
    from peewee import SQL, Query, RawQuery, SelectQuery, NoopSelectQuery
ImportError: cannot import name 'NoopSelectQuery'
```
What happen?
Modules is installed

**Comment by kszucs** [comment]
What peewee version are You using?

**Comment by kobelover** [comment]
peewee            3.3.4
aiopeewee         0.4.2

**Comment by kszucs** [comment]
It's probably caused by the new version of peewee. Aiopeewee is currently compatible with `peewee<3.0`. Please try to downgrade peewee to `2.9`

**Comment by kobelover** [comment]
ok, thanks kszucs.

**Comment by kszucs** [comment]
You're welcome. We should pin this in `setup.py` though.

**Comment by awilliamson** [comment]
An addition to the readme would also go a long way in saving time for people.
